namespace Bank.Logic.Abstractions;

// do not edit this file

public interface IAccount
{
    int Id { get; set; }
    AccountSettings Settings { get; set; }
    List<ITransaction> Transactions { get; set; }
    IReadOnlyList<ITransaction> GetTransactions();
    bool TryAddTransaction(ITransaction transaction);
    double GetBalance();
}
